### ISSUE TITLE
Manual should contain guidance on digipeater/igate identification

### ISSUE THREAD

**Issue by dandrzejewski** [PhirePhly/aprx#40]
http://www.aprs.org/digis/digi-rates.txt contains information on how digipeaters/igates should identify themselves.

The manual should contain information on how to configure this.

**Comment by PhirePhly** [comment]
I think this is too broad of an issue to fall on the shoulders of being documented in the Aprx manual. Bob's edict on proportional pathing is not the only answer to how APRS stations should identify, digipeater/I-gate or otherwise, so the complete discussion on exactly how stations should beacon their ID goes well beyond a manual on how to operate Aprx. 

Duplicating the same discussion across every APRS project would only cause confusion. These sorts of guides should be more centralized and portable.
